
INSERT INTO employee (last_name, first_name, birth_date, address, city, country, reports_to) VALUES
('GOMEZ','JUAN','1980-01-15','CALLE 1','QUITO','ECUADOR',NULL),
('PEREZ','MARIA','1985-03-22','CALLE 2','GUAYAQUIL','ECUADOR',1),
('LOPEZ','CARLOS','1990-07-10','CALLE 3','CUENCA','ECUADOR',1),
('MARTINEZ','LAURA','1982-11-05','CALLE 4','QUITO','ECUADOR',2),
('RODRIGUEZ','PEDRO','1978-06-30','CALLE 5','GUAYAQUIL','ECUADOR',2),
('GARCIA','ANA','1992-12-12','CALLE 6','CUENCA','ECUADOR',3),
('HERRERA','LUIS','1987-04-18','CALLE 7','QUITO','ECUADOR',3),
('SANCHEZ','CARLA','1991-09-25','CALLE 8','GUAYAQUIL','ECUADOR',4),
('MORALES','JAVIER','1983-02-14','CALLE 9','CUENCA','ECUADOR',4),
('RAMIREZ','SOFIA','1989-08-09','CALLE 10','QUITO','ECUADOR',5),
('TORRES','RICARDO','1986-05-20','CALLE 11','GUAYAQUIL','ECUADOR',5),
('CASTRO','ELENA','1993-07-30','CALLE 12','CUENCA','ECUADOR',6),
('RIVERA','DIEGO','1981-10-10','CALLE 13','QUITO','ECUADOR',6),
('CRUZ','VALERIA','1988-03-03','CALLE 14','GUAYAQUIL','ECUADOR',7),
('MENDOZA','ANDRES','1979-12-22','CALLE 15','CUENCA','ECUADOR',7),
('GUERRERO','PATRICIA','1994-01-18','CALLE 16','QUITO','ECUADOR',8),
('VARGAS','FERNANDO','1985-06-06','CALLE 17','GUAYAQUIL','ECUADOR',8),
('IBARRA','MONICA','1990-09-14','CALLE 18','CUENCA','ECUADOR',9),
('SALAZAR','JORGE','1982-02-28','CALLE 19','QUITO','ECUADOR',9),
('ALVAREZ','LILIANA','1987-11-11','CALLE 20','GUAYAQUIL','ECUADOR',10);


select * from employee;

INSERT INTO customer (contact_name, company_name, contact_email, address, city, country) VALUES
('JUAN PEREZ','EMPRESA A','JUAN@EMPRESAA.COM','CALLE 1','QUITO','ECUADOR'),
('MARIA LOPEZ','EMPRESA B','MARIA@EMPRESAB.COM','CALLE 2','GUAYAQUIL','ECUADOR'),
('CARLOS MARTINEZ','EMPRESA C','CARLOS@EMPRESAC.COM','CALLE 3','CUENCA','ECUADOR'),
('LAURA RODRIGUEZ','EMPRESA D','LAURA@EMPRESAD.COM','CALLE 4','QUITO','ECUADOR'),
('PEDRO GARCIA','EMPRESA E','PEDRO@EMPRESAE.COM','CALLE 5','GUAYAQUIL','ECUADOR'),
('ANA HERRERA','EMPRESA F','ANA@EMPRESAF.COM','CALLE 6','CUENCA','ECUADOR'),
('LUIS SANCHEZ','EMPRESA G','LUIS@EMPRESAG.COM','CALLE 7','QUITO','ECUADOR'),
('CARLA MORALES','EMPRESA H','CARLA@EMPRESAH.COM','CALLE 8','GUAYAQUIL','ECUADOR'),
('JAVIER RAMIREZ','EMPRESA I','JAVIER@EMPRESAI.COM','CALLE 9','CUENCA','ECUADOR'),
('SOFIA TORRES','EMPRESA J','SOFIA@EMPRESAJ.COM','CALLE 10','QUITO','ECUADOR'),
('RICARDO CASTRO','EMPRESA K','RICARDO@EMPRESAK.COM','CALLE 11','GUAYAQUIL','ECUADOR'),
('ELENA RIVERA','EMPRESA L','ELENA@EMPRESAL.COM','CALLE 12','CUENCA','ECUADOR'),
('DIEGO CRUZ','EMPRESA M','DIEGO@EMPRESAM.COM','CALLE 13','QUITO','ECUADOR'),
('VALERIA MENDOZA','EMPRESA N','VALERIA@EMPRESAN.COM','CALLE 14','GUAYAQUIL','ECUADOR'),
('ANDRES GUERRERO','EMPRESA O','ANDRES@EMPRESAO.COM','CALLE 15','CUENCA','ECUADOR'),
('PATRICIA VARGAS','EMPRESA P','PATRICIA@EMPRESAP.COM','CALLE 16','QUITO','ECUADOR'),
('FERNANDO IBARRA','EMPRESA Q','FERNANDO@EMPRESAQ.COM','CALLE 17','GUAYAQUIL','ECUADOR'),
('MONICA SALAZAR','EMPRESA R','MONICA@EMPRESAR.COM','CALLE 18','CUENCA','ECUADOR'),
('JORGE ALVAREZ','EMPRESA S','JORGE@EMPRESAS.COM','CALLE 19','QUITO','ECUADOR'),
('LILIANA GOMEZ','EMPRESA T','LILIANA@EMPRESAT.COM','CALLE 20','GUAYAQUIL','ECUADOR');


INSERT INTO category (name, description, parent_category_id) VALUES
('ELECTRONICA','DISPOSITIVOS ELECTRONICOS',NULL),
('COMPUTACION','EQUIPOS DE COMPUTO',1),
('CELULARES','SMARTPHONES Y ACCESORIOS',1),
('HOGAR','PRODUCTOS PARA EL HOGAR',NULL),
('COCINA','UTENSILIOS DE COCINA',4),
('MUEBLES','MUEBLES PARA EL HOGAR',4),
('MODA','ROPA Y ACCESORIOS',NULL),
('CALZADO','ZAPATOS Y SANDALIAS',7),
('DEPORTES','ARTICULOS DEPORTIVOS',NULL),
('JUGUETES','JUGUETES Y JUEGOS',NULL),
('VIDEOJUEGOS','CONSOLA Y VIDEOJUEGOS',1),
('TABLETS','TABLETS Y ACCESORIOS',2),
('CAMARAS','CAMARAS FOTOGRAFICAS',1),
('TELEVISORES','TELEVISORES Y MONITORES',1),
('HELADERAS','HELADERAS Y NEVERAS',4),
('LAVADORAS','LAVADORAS Y SECADORAS',4),
('RELOJES','RELOJES Y ACCESORIOS',7),
('BOLSOS','BOLSOS Y MOCHILAS',7),
('BICICLETAS','BICICLETAS Y ACCESORIOS',9),
('PELOTAS','PELOTAS Y BALONES',9);

INSERT INTO product (product_name, category_id, quantity_per_unit, unit_price, units_in_stock, discontinued) VALUES
('LAPTOP HP','2','1 UNIDAD','1200.00','50',FALSE),
('SMARTPHONE SAMSUNG','3','1 UNIDAD','800.00','100',FALSE),
('CAMARA CANON','13','1 UNIDAD','500.00','30',FALSE),
('TELEVISOR LG','14','1 UNIDAD','700.00','25',FALSE),
('HELADERA WHIRLPOOL','15','1 UNIDAD','900.00','15',FALSE),
('LAVADORA LG','16','1 UNIDAD','650.00','20',FALSE),
('RELOJ CASIO','17','1 UNIDAD','50.00','200',FALSE),
('BOLSO MICHAEL KORS','18','1 UNIDAD','120.00','80',FALSE),
('BICICLETA TREK','19','1 UNIDAD','400.00','40',FALSE),
('PELOTA ADIDAS','20','1 UNIDAD','30.00','150',FALSE),
('TABLET SAMSUNG','12','1 UNIDAD','350.00','60',FALSE),
('LAPTOP DELL','2','1 UNIDAD','1100.00','45',FALSE),
('SMARTPHONE IPHONE','3','1 UNIDAD','1000.00','70',FALSE),
('CAMARA NIKON','13','1 UNIDAD','600.00','25',FALSE),
('TELEVISOR SONY','14','1 UNIDAD','750.00','30',FALSE),
('HELADERA LG','15','1 UNIDAD','950.00','10',FALSE),
('LAVADORA SAMSUNG','16','1 UNIDAD','700.00','18',FALSE),
('RELOJ FOSSIL','17','1 UNIDAD','80.00','90',FALSE),
('BOLSO GUCCI','18','1 UNIDAD','200.00','50',FALSE),
('BICICLETA GIANT','19','1 UNIDAD','450.00','35',FALSE);

select * from product;

select * from category;
//discontinuo ya no se venden "true"
// continuo aun siguen activo stock "false"
----ejericio13---
SELECT 
	c.name AS nombre_categoria,
	COUNT(*) FILTER (WHERE discontinued = true) discontinued_products,
	COUNT(*) FILTER (WHERE discontinued = false) continued_products,
	COUNT(*) AS all_products
FROM category c
	LEFT JOIN product p
		ON c.category_id = p.category_id
GROUP BY c.category_id
ORDER BY c.name;

------ejercicio15----
SELECT 
    pi.purchase_id,
    COUNT(DISTINCT p.category_id) AS num_categorias
FROM purchase_item pi
	JOIN product p 
    	ON p.product_id = pi.product_id
GROUP BY pi.purchase_id;

--
SELECT MAX(num_categorias) AS max_categorias
FROM (
    SELECT 
        pi.purchase_id,
        COUNT(DISTINCT p.category_id) AS num_categorias
    FROM purchase_item pi
    JOIN product p 
        ON p.product_id = pi.product_id
    GROUP BY pi.purchase_id
) 

